/*
Celenium API

Celenium API is a powerful tool to access all blockchain data that is processed and indexed by our proprietary indexer. With Celenium API you can retrieve all historical data, off-chain data, blobs and statistics through our REST API. Celenium API indexer are open source, which allows you to not depend on third-party services. You can clone, build and run them independently, giving you full control over all components. If you have any questions or feature requests, please feel free to contact us. We appreciate your feedback!

API version: 1.0
Contact: celenium@pklabs.me
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package celenium

import (
	"encoding/json"
	"os"
	"time"
)

// checks if the ResponsesIbcChannel type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ResponsesIbcChannel{}

// ResponsesIbcChannel struct for ResponsesIbcChannel
type ResponsesIbcChannel struct {
	Client *ResponsesShortIbcClient `json:"client,omitempty"`
	ConfirmationHeight *int32 `json:"confirmation_height,omitempty"`
	ConfirmationTxHash **os.File `json:"confirmation_tx_hash,omitempty"`
	ConfirmedAt *time.Time `json:"confirmed_at,omitempty"`
	ConnectionId *string `json:"connection_id,omitempty"`
	CounterpartyChannelId *string `json:"counterparty_channel_id,omitempty"`
	CounterpartyPortId *string `json:"counterparty_port_id,omitempty"`
	CreatedAt *time.Time `json:"created_at,omitempty"`
	CreatedTxHash **os.File `json:"created_tx_hash,omitempty"`
	Creator *ResponsesShortAddress `json:"creator,omitempty"`
	Height *int32 `json:"height,omitempty"`
	Id *string `json:"id,omitempty"`
	Ordering *bool `json:"ordering,omitempty"`
	PortId *string `json:"port_id,omitempty"`
	Status *string `json:"status,omitempty"`
	Version *string `json:"version,omitempty"`
}

// NewResponsesIbcChannel instantiates a new ResponsesIbcChannel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResponsesIbcChannel() *ResponsesIbcChannel {
	this := ResponsesIbcChannel{}
	return &this
}

// NewResponsesIbcChannelWithDefaults instantiates a new ResponsesIbcChannel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResponsesIbcChannelWithDefaults() *ResponsesIbcChannel {
	this := ResponsesIbcChannel{}
	return &this
}

// GetClient returns the Client field value if set, zero value otherwise.
func (o *ResponsesIbcChannel) GetClient() ResponsesShortIbcClient {
	if o == nil || IsNil(o.Client) {
		var ret ResponsesShortIbcClient
		return ret
	}
	return *o.Client
}

// GetClientOk returns a tuple with the Client field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponsesIbcChannel) GetClientOk() (*ResponsesShortIbcClient, bool) {
	if o == nil || IsNil(o.Client) {
		return nil, false
	}
	return o.Client, true
}

// HasClient returns a boolean if a field has been set.
func (o *ResponsesIbcChannel) HasClient() bool {
	if o != nil && !IsNil(o.Client) {
		return true
	}

	return false
}

// SetClient gets a reference to the given ResponsesShortIbcClient and assigns it to the Client field.
func (o *ResponsesIbcChannel) SetClient(v ResponsesShortIbcClient) {
	o.Client = &v
}

// GetConfirmationHeight returns the ConfirmationHeight field value if set, zero value otherwise.
func (o *ResponsesIbcChannel) GetConfirmationHeight() int32 {
	if o == nil || IsNil(o.ConfirmationHeight) {
		var ret int32
		return ret
	}
	return *o.ConfirmationHeight
}

// GetConfirmationHeightOk returns a tuple with the ConfirmationHeight field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponsesIbcChannel) GetConfirmationHeightOk() (*int32, bool) {
	if o == nil || IsNil(o.ConfirmationHeight) {
		return nil, false
	}
	return o.ConfirmationHeight, true
}

// HasConfirmationHeight returns a boolean if a field has been set.
func (o *ResponsesIbcChannel) HasConfirmationHeight() bool {
	if o != nil && !IsNil(o.ConfirmationHeight) {
		return true
	}

	return false
}

// SetConfirmationHeight gets a reference to the given int32 and assigns it to the ConfirmationHeight field.
func (o *ResponsesIbcChannel) SetConfirmationHeight(v int32) {
	o.ConfirmationHeight = &v
}

// GetConfirmationTxHash returns the ConfirmationTxHash field value if set, zero value otherwise.
func (o *ResponsesIbcChannel) GetConfirmationTxHash() *os.File {
	if o == nil || IsNil(o.ConfirmationTxHash) {
		var ret *os.File
		return ret
	}
	return *o.ConfirmationTxHash
}

// GetConfirmationTxHashOk returns a tuple with the ConfirmationTxHash field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponsesIbcChannel) GetConfirmationTxHashOk() (**os.File, bool) {
	if o == nil || IsNil(o.ConfirmationTxHash) {
		return nil, false
	}
	return o.ConfirmationTxHash, true
}

// HasConfirmationTxHash returns a boolean if a field has been set.
func (o *ResponsesIbcChannel) HasConfirmationTxHash() bool {
	if o != nil && !IsNil(o.ConfirmationTxHash) {
		return true
	}

	return false
}

// SetConfirmationTxHash gets a reference to the given *os.File and assigns it to the ConfirmationTxHash field.
func (o *ResponsesIbcChannel) SetConfirmationTxHash(v *os.File) {
	o.ConfirmationTxHash = &v
}

// GetConfirmedAt returns the ConfirmedAt field value if set, zero value otherwise.
func (o *ResponsesIbcChannel) GetConfirmedAt() time.Time {
	if o == nil || IsNil(o.ConfirmedAt) {
		var ret time.Time
		return ret
	}
	return *o.ConfirmedAt
}

// GetConfirmedAtOk returns a tuple with the ConfirmedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponsesIbcChannel) GetConfirmedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.ConfirmedAt) {
		return nil, false
	}
	return o.ConfirmedAt, true
}

// HasConfirmedAt returns a boolean if a field has been set.
func (o *ResponsesIbcChannel) HasConfirmedAt() bool {
	if o != nil && !IsNil(o.ConfirmedAt) {
		return true
	}

	return false
}

// SetConfirmedAt gets a reference to the given time.Time and assigns it to the ConfirmedAt field.
func (o *ResponsesIbcChannel) SetConfirmedAt(v time.Time) {
	o.ConfirmedAt = &v
}

// GetConnectionId returns the ConnectionId field value if set, zero value otherwise.
func (o *ResponsesIbcChannel) GetConnectionId() string {
	if o == nil || IsNil(o.ConnectionId) {
		var ret string
		return ret
	}
	return *o.ConnectionId
}

// GetConnectionIdOk returns a tuple with the ConnectionId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponsesIbcChannel) GetConnectionIdOk() (*string, bool) {
	if o == nil || IsNil(o.ConnectionId) {
		return nil, false
	}
	return o.ConnectionId, true
}

// HasConnectionId returns a boolean if a field has been set.
func (o *ResponsesIbcChannel) HasConnectionId() bool {
	if o != nil && !IsNil(o.ConnectionId) {
		return true
	}

	return false
}

// SetConnectionId gets a reference to the given string and assigns it to the ConnectionId field.
func (o *ResponsesIbcChannel) SetConnectionId(v string) {
	o.ConnectionId = &v
}

// GetCounterpartyChannelId returns the CounterpartyChannelId field value if set, zero value otherwise.
func (o *ResponsesIbcChannel) GetCounterpartyChannelId() string {
	if o == nil || IsNil(o.CounterpartyChannelId) {
		var ret string
		return ret
	}
	return *o.CounterpartyChannelId
}

// GetCounterpartyChannelIdOk returns a tuple with the CounterpartyChannelId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponsesIbcChannel) GetCounterpartyChannelIdOk() (*string, bool) {
	if o == nil || IsNil(o.CounterpartyChannelId) {
		return nil, false
	}
	return o.CounterpartyChannelId, true
}

// HasCounterpartyChannelId returns a boolean if a field has been set.
func (o *ResponsesIbcChannel) HasCounterpartyChannelId() bool {
	if o != nil && !IsNil(o.CounterpartyChannelId) {
		return true
	}

	return false
}

// SetCounterpartyChannelId gets a reference to the given string and assigns it to the CounterpartyChannelId field.
func (o *ResponsesIbcChannel) SetCounterpartyChannelId(v string) {
	o.CounterpartyChannelId = &v
}

// GetCounterpartyPortId returns the CounterpartyPortId field value if set, zero value otherwise.
func (o *ResponsesIbcChannel) GetCounterpartyPortId() string {
	if o == nil || IsNil(o.CounterpartyPortId) {
		var ret string
		return ret
	}
	return *o.CounterpartyPortId
}

// GetCounterpartyPortIdOk returns a tuple with the CounterpartyPortId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponsesIbcChannel) GetCounterpartyPortIdOk() (*string, bool) {
	if o == nil || IsNil(o.CounterpartyPortId) {
		return nil, false
	}
	return o.CounterpartyPortId, true
}

// HasCounterpartyPortId returns a boolean if a field has been set.
func (o *ResponsesIbcChannel) HasCounterpartyPortId() bool {
	if o != nil && !IsNil(o.CounterpartyPortId) {
		return true
	}

	return false
}

// SetCounterpartyPortId gets a reference to the given string and assigns it to the CounterpartyPortId field.
func (o *ResponsesIbcChannel) SetCounterpartyPortId(v string) {
	o.CounterpartyPortId = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *ResponsesIbcChannel) GetCreatedAt() time.Time {
	if o == nil || IsNil(o.CreatedAt) {
		var ret time.Time
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponsesIbcChannel) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *ResponsesIbcChannel) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given time.Time and assigns it to the CreatedAt field.
func (o *ResponsesIbcChannel) SetCreatedAt(v time.Time) {
	o.CreatedAt = &v
}

// GetCreatedTxHash returns the CreatedTxHash field value if set, zero value otherwise.
func (o *ResponsesIbcChannel) GetCreatedTxHash() *os.File {
	if o == nil || IsNil(o.CreatedTxHash) {
		var ret *os.File
		return ret
	}
	return *o.CreatedTxHash
}

// GetCreatedTxHashOk returns a tuple with the CreatedTxHash field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponsesIbcChannel) GetCreatedTxHashOk() (**os.File, bool) {
	if o == nil || IsNil(o.CreatedTxHash) {
		return nil, false
	}
	return o.CreatedTxHash, true
}

// HasCreatedTxHash returns a boolean if a field has been set.
func (o *ResponsesIbcChannel) HasCreatedTxHash() bool {
	if o != nil && !IsNil(o.CreatedTxHash) {
		return true
	}

	return false
}

// SetCreatedTxHash gets a reference to the given *os.File and assigns it to the CreatedTxHash field.
func (o *ResponsesIbcChannel) SetCreatedTxHash(v *os.File) {
	o.CreatedTxHash = &v
}

// GetCreator returns the Creator field value if set, zero value otherwise.
func (o *ResponsesIbcChannel) GetCreator() ResponsesShortAddress {
	if o == nil || IsNil(o.Creator) {
		var ret ResponsesShortAddress
		return ret
	}
	return *o.Creator
}

// GetCreatorOk returns a tuple with the Creator field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponsesIbcChannel) GetCreatorOk() (*ResponsesShortAddress, bool) {
	if o == nil || IsNil(o.Creator) {
		return nil, false
	}
	return o.Creator, true
}

// HasCreator returns a boolean if a field has been set.
func (o *ResponsesIbcChannel) HasCreator() bool {
	if o != nil && !IsNil(o.Creator) {
		return true
	}

	return false
}

// SetCreator gets a reference to the given ResponsesShortAddress and assigns it to the Creator field.
func (o *ResponsesIbcChannel) SetCreator(v ResponsesShortAddress) {
	o.Creator = &v
}

// GetHeight returns the Height field value if set, zero value otherwise.
func (o *ResponsesIbcChannel) GetHeight() int32 {
	if o == nil || IsNil(o.Height) {
		var ret int32
		return ret
	}
	return *o.Height
}

// GetHeightOk returns a tuple with the Height field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponsesIbcChannel) GetHeightOk() (*int32, bool) {
	if o == nil || IsNil(o.Height) {
		return nil, false
	}
	return o.Height, true
}

// HasHeight returns a boolean if a field has been set.
func (o *ResponsesIbcChannel) HasHeight() bool {
	if o != nil && !IsNil(o.Height) {
		return true
	}

	return false
}

// SetHeight gets a reference to the given int32 and assigns it to the Height field.
func (o *ResponsesIbcChannel) SetHeight(v int32) {
	o.Height = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *ResponsesIbcChannel) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponsesIbcChannel) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *ResponsesIbcChannel) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *ResponsesIbcChannel) SetId(v string) {
	o.Id = &v
}

// GetOrdering returns the Ordering field value if set, zero value otherwise.
func (o *ResponsesIbcChannel) GetOrdering() bool {
	if o == nil || IsNil(o.Ordering) {
		var ret bool
		return ret
	}
	return *o.Ordering
}

// GetOrderingOk returns a tuple with the Ordering field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponsesIbcChannel) GetOrderingOk() (*bool, bool) {
	if o == nil || IsNil(o.Ordering) {
		return nil, false
	}
	return o.Ordering, true
}

// HasOrdering returns a boolean if a field has been set.
func (o *ResponsesIbcChannel) HasOrdering() bool {
	if o != nil && !IsNil(o.Ordering) {
		return true
	}

	return false
}

// SetOrdering gets a reference to the given bool and assigns it to the Ordering field.
func (o *ResponsesIbcChannel) SetOrdering(v bool) {
	o.Ordering = &v
}

// GetPortId returns the PortId field value if set, zero value otherwise.
func (o *ResponsesIbcChannel) GetPortId() string {
	if o == nil || IsNil(o.PortId) {
		var ret string
		return ret
	}
	return *o.PortId
}

// GetPortIdOk returns a tuple with the PortId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponsesIbcChannel) GetPortIdOk() (*string, bool) {
	if o == nil || IsNil(o.PortId) {
		return nil, false
	}
	return o.PortId, true
}

// HasPortId returns a boolean if a field has been set.
func (o *ResponsesIbcChannel) HasPortId() bool {
	if o != nil && !IsNil(o.PortId) {
		return true
	}

	return false
}

// SetPortId gets a reference to the given string and assigns it to the PortId field.
func (o *ResponsesIbcChannel) SetPortId(v string) {
	o.PortId = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *ResponsesIbcChannel) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponsesIbcChannel) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *ResponsesIbcChannel) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *ResponsesIbcChannel) SetStatus(v string) {
	o.Status = &v
}

// GetVersion returns the Version field value if set, zero value otherwise.
func (o *ResponsesIbcChannel) GetVersion() string {
	if o == nil || IsNil(o.Version) {
		var ret string
		return ret
	}
	return *o.Version
}

// GetVersionOk returns a tuple with the Version field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponsesIbcChannel) GetVersionOk() (*string, bool) {
	if o == nil || IsNil(o.Version) {
		return nil, false
	}
	return o.Version, true
}

// HasVersion returns a boolean if a field has been set.
func (o *ResponsesIbcChannel) HasVersion() bool {
	if o != nil && !IsNil(o.Version) {
		return true
	}

	return false
}

// SetVersion gets a reference to the given string and assigns it to the Version field.
func (o *ResponsesIbcChannel) SetVersion(v string) {
	o.Version = &v
}

func (o ResponsesIbcChannel) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ResponsesIbcChannel) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Client) {
		toSerialize["client"] = o.Client
	}
	if !IsNil(o.ConfirmationHeight) {
		toSerialize["confirmation_height"] = o.ConfirmationHeight
	}
	if !IsNil(o.ConfirmationTxHash) {
		toSerialize["confirmation_tx_hash"] = o.ConfirmationTxHash
	}
	if !IsNil(o.ConfirmedAt) {
		toSerialize["confirmed_at"] = o.ConfirmedAt
	}
	if !IsNil(o.ConnectionId) {
		toSerialize["connection_id"] = o.ConnectionId
	}
	if !IsNil(o.CounterpartyChannelId) {
		toSerialize["counterparty_channel_id"] = o.CounterpartyChannelId
	}
	if !IsNil(o.CounterpartyPortId) {
		toSerialize["counterparty_port_id"] = o.CounterpartyPortId
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["created_at"] = o.CreatedAt
	}
	if !IsNil(o.CreatedTxHash) {
		toSerialize["created_tx_hash"] = o.CreatedTxHash
	}
	if !IsNil(o.Creator) {
		toSerialize["creator"] = o.Creator
	}
	if !IsNil(o.Height) {
		toSerialize["height"] = o.Height
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Ordering) {
		toSerialize["ordering"] = o.Ordering
	}
	if !IsNil(o.PortId) {
		toSerialize["port_id"] = o.PortId
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.Version) {
		toSerialize["version"] = o.Version
	}
	return toSerialize, nil
}

type NullableResponsesIbcChannel struct {
	value *ResponsesIbcChannel
	isSet bool
}

func (v NullableResponsesIbcChannel) Get() *ResponsesIbcChannel {
	return v.value
}

func (v *NullableResponsesIbcChannel) Set(val *ResponsesIbcChannel) {
	v.value = val
	v.isSet = true
}

func (v NullableResponsesIbcChannel) IsSet() bool {
	return v.isSet
}

func (v *NullableResponsesIbcChannel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResponsesIbcChannel(val *ResponsesIbcChannel) *NullableResponsesIbcChannel {
	return &NullableResponsesIbcChannel{value: val, isSet: true}
}

func (v NullableResponsesIbcChannel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResponsesIbcChannel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


