/*
Celenium API

Celenium API is a powerful tool to access all blockchain data that is processed and indexed by our proprietary indexer. With Celenium API you can retrieve all historical data, off-chain data, blobs and statistics through our REST API. Celenium API indexer are open source, which allows you to not depend on third-party services. You can clone, build and run them independently, giving you full control over all components. If you have any questions or feature requests, please feel free to contact us. We appreciate your feedback!

API version: 1.0
Contact: celenium@pklabs.me
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package celenium

import (
	"encoding/json"
	"os"
	"time"
)

// checks if the ResponsesIbcClient type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ResponsesIbcClient{}

// ResponsesIbcClient struct for ResponsesIbcClient
type ResponsesIbcClient struct {
	ChainId **os.File `json:"chain_id,omitempty"`
	ConnectionCount *int32 `json:"connection_count,omitempty"`
	CreatedAt *time.Time `json:"created_at,omitempty"`
	Creator *ResponsesShortAddress `json:"creator,omitempty"`
	FrozenRevisionHeight *int32 `json:"frozen_revision_height,omitempty"`
	FrozenRevisionNumber *int32 `json:"frozen_revision_number,omitempty"`
	Height *int32 `json:"height,omitempty"`
	Id *string `json:"id,omitempty"`
	LatestRevisionHeight *int32 `json:"latest_revision_height,omitempty"`
	LatestRevisionNumber *int32 `json:"latest_revision_number,omitempty"`
	MaxClockDrift *int32 `json:"max_clock_drift,omitempty"`
	TrustLevelDenominator *int32 `json:"trust_level_denominator,omitempty"`
	TrustLevelNumerator *int32 `json:"trust_level_numerator,omitempty"`
	TrustingPeriod *int32 `json:"trusting_period,omitempty"`
	TxHash **os.File `json:"tx_hash,omitempty"`
	Type *string `json:"type,omitempty"`
	UnbondingPeriod *int32 `json:"unbonding_period,omitempty"`
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
}

// NewResponsesIbcClient instantiates a new ResponsesIbcClient object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResponsesIbcClient() *ResponsesIbcClient {
	this := ResponsesIbcClient{}
	return &this
}

// NewResponsesIbcClientWithDefaults instantiates a new ResponsesIbcClient object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResponsesIbcClientWithDefaults() *ResponsesIbcClient {
	this := ResponsesIbcClient{}
	return &this
}

// GetChainId returns the ChainId field value if set, zero value otherwise.
func (o *ResponsesIbcClient) GetChainId() *os.File {
	if o == nil || IsNil(o.ChainId) {
		var ret *os.File
		return ret
	}
	return *o.ChainId
}

// GetChainIdOk returns a tuple with the ChainId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponsesIbcClient) GetChainIdOk() (**os.File, bool) {
	if o == nil || IsNil(o.ChainId) {
		return nil, false
	}
	return o.ChainId, true
}

// HasChainId returns a boolean if a field has been set.
func (o *ResponsesIbcClient) HasChainId() bool {
	if o != nil && !IsNil(o.ChainId) {
		return true
	}

	return false
}

// SetChainId gets a reference to the given *os.File and assigns it to the ChainId field.
func (o *ResponsesIbcClient) SetChainId(v *os.File) {
	o.ChainId = &v
}

// GetConnectionCount returns the ConnectionCount field value if set, zero value otherwise.
func (o *ResponsesIbcClient) GetConnectionCount() int32 {
	if o == nil || IsNil(o.ConnectionCount) {
		var ret int32
		return ret
	}
	return *o.ConnectionCount
}

// GetConnectionCountOk returns a tuple with the ConnectionCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponsesIbcClient) GetConnectionCountOk() (*int32, bool) {
	if o == nil || IsNil(o.ConnectionCount) {
		return nil, false
	}
	return o.ConnectionCount, true
}

// HasConnectionCount returns a boolean if a field has been set.
func (o *ResponsesIbcClient) HasConnectionCount() bool {
	if o != nil && !IsNil(o.ConnectionCount) {
		return true
	}

	return false
}

// SetConnectionCount gets a reference to the given int32 and assigns it to the ConnectionCount field.
func (o *ResponsesIbcClient) SetConnectionCount(v int32) {
	o.ConnectionCount = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *ResponsesIbcClient) GetCreatedAt() time.Time {
	if o == nil || IsNil(o.CreatedAt) {
		var ret time.Time
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponsesIbcClient) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *ResponsesIbcClient) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given time.Time and assigns it to the CreatedAt field.
func (o *ResponsesIbcClient) SetCreatedAt(v time.Time) {
	o.CreatedAt = &v
}

// GetCreator returns the Creator field value if set, zero value otherwise.
func (o *ResponsesIbcClient) GetCreator() ResponsesShortAddress {
	if o == nil || IsNil(o.Creator) {
		var ret ResponsesShortAddress
		return ret
	}
	return *o.Creator
}

// GetCreatorOk returns a tuple with the Creator field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponsesIbcClient) GetCreatorOk() (*ResponsesShortAddress, bool) {
	if o == nil || IsNil(o.Creator) {
		return nil, false
	}
	return o.Creator, true
}

// HasCreator returns a boolean if a field has been set.
func (o *ResponsesIbcClient) HasCreator() bool {
	if o != nil && !IsNil(o.Creator) {
		return true
	}

	return false
}

// SetCreator gets a reference to the given ResponsesShortAddress and assigns it to the Creator field.
func (o *ResponsesIbcClient) SetCreator(v ResponsesShortAddress) {
	o.Creator = &v
}

// GetFrozenRevisionHeight returns the FrozenRevisionHeight field value if set, zero value otherwise.
func (o *ResponsesIbcClient) GetFrozenRevisionHeight() int32 {
	if o == nil || IsNil(o.FrozenRevisionHeight) {
		var ret int32
		return ret
	}
	return *o.FrozenRevisionHeight
}

// GetFrozenRevisionHeightOk returns a tuple with the FrozenRevisionHeight field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponsesIbcClient) GetFrozenRevisionHeightOk() (*int32, bool) {
	if o == nil || IsNil(o.FrozenRevisionHeight) {
		return nil, false
	}
	return o.FrozenRevisionHeight, true
}

// HasFrozenRevisionHeight returns a boolean if a field has been set.
func (o *ResponsesIbcClient) HasFrozenRevisionHeight() bool {
	if o != nil && !IsNil(o.FrozenRevisionHeight) {
		return true
	}

	return false
}

// SetFrozenRevisionHeight gets a reference to the given int32 and assigns it to the FrozenRevisionHeight field.
func (o *ResponsesIbcClient) SetFrozenRevisionHeight(v int32) {
	o.FrozenRevisionHeight = &v
}

// GetFrozenRevisionNumber returns the FrozenRevisionNumber field value if set, zero value otherwise.
func (o *ResponsesIbcClient) GetFrozenRevisionNumber() int32 {
	if o == nil || IsNil(o.FrozenRevisionNumber) {
		var ret int32
		return ret
	}
	return *o.FrozenRevisionNumber
}

// GetFrozenRevisionNumberOk returns a tuple with the FrozenRevisionNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponsesIbcClient) GetFrozenRevisionNumberOk() (*int32, bool) {
	if o == nil || IsNil(o.FrozenRevisionNumber) {
		return nil, false
	}
	return o.FrozenRevisionNumber, true
}

// HasFrozenRevisionNumber returns a boolean if a field has been set.
func (o *ResponsesIbcClient) HasFrozenRevisionNumber() bool {
	if o != nil && !IsNil(o.FrozenRevisionNumber) {
		return true
	}

	return false
}

// SetFrozenRevisionNumber gets a reference to the given int32 and assigns it to the FrozenRevisionNumber field.
func (o *ResponsesIbcClient) SetFrozenRevisionNumber(v int32) {
	o.FrozenRevisionNumber = &v
}

// GetHeight returns the Height field value if set, zero value otherwise.
func (o *ResponsesIbcClient) GetHeight() int32 {
	if o == nil || IsNil(o.Height) {
		var ret int32
		return ret
	}
	return *o.Height
}

// GetHeightOk returns a tuple with the Height field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponsesIbcClient) GetHeightOk() (*int32, bool) {
	if o == nil || IsNil(o.Height) {
		return nil, false
	}
	return o.Height, true
}

// HasHeight returns a boolean if a field has been set.
func (o *ResponsesIbcClient) HasHeight() bool {
	if o != nil && !IsNil(o.Height) {
		return true
	}

	return false
}

// SetHeight gets a reference to the given int32 and assigns it to the Height field.
func (o *ResponsesIbcClient) SetHeight(v int32) {
	o.Height = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *ResponsesIbcClient) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponsesIbcClient) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *ResponsesIbcClient) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *ResponsesIbcClient) SetId(v string) {
	o.Id = &v
}

// GetLatestRevisionHeight returns the LatestRevisionHeight field value if set, zero value otherwise.
func (o *ResponsesIbcClient) GetLatestRevisionHeight() int32 {
	if o == nil || IsNil(o.LatestRevisionHeight) {
		var ret int32
		return ret
	}
	return *o.LatestRevisionHeight
}

// GetLatestRevisionHeightOk returns a tuple with the LatestRevisionHeight field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponsesIbcClient) GetLatestRevisionHeightOk() (*int32, bool) {
	if o == nil || IsNil(o.LatestRevisionHeight) {
		return nil, false
	}
	return o.LatestRevisionHeight, true
}

// HasLatestRevisionHeight returns a boolean if a field has been set.
func (o *ResponsesIbcClient) HasLatestRevisionHeight() bool {
	if o != nil && !IsNil(o.LatestRevisionHeight) {
		return true
	}

	return false
}

// SetLatestRevisionHeight gets a reference to the given int32 and assigns it to the LatestRevisionHeight field.
func (o *ResponsesIbcClient) SetLatestRevisionHeight(v int32) {
	o.LatestRevisionHeight = &v
}

// GetLatestRevisionNumber returns the LatestRevisionNumber field value if set, zero value otherwise.
func (o *ResponsesIbcClient) GetLatestRevisionNumber() int32 {
	if o == nil || IsNil(o.LatestRevisionNumber) {
		var ret int32
		return ret
	}
	return *o.LatestRevisionNumber
}

// GetLatestRevisionNumberOk returns a tuple with the LatestRevisionNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponsesIbcClient) GetLatestRevisionNumberOk() (*int32, bool) {
	if o == nil || IsNil(o.LatestRevisionNumber) {
		return nil, false
	}
	return o.LatestRevisionNumber, true
}

// HasLatestRevisionNumber returns a boolean if a field has been set.
func (o *ResponsesIbcClient) HasLatestRevisionNumber() bool {
	if o != nil && !IsNil(o.LatestRevisionNumber) {
		return true
	}

	return false
}

// SetLatestRevisionNumber gets a reference to the given int32 and assigns it to the LatestRevisionNumber field.
func (o *ResponsesIbcClient) SetLatestRevisionNumber(v int32) {
	o.LatestRevisionNumber = &v
}

// GetMaxClockDrift returns the MaxClockDrift field value if set, zero value otherwise.
func (o *ResponsesIbcClient) GetMaxClockDrift() int32 {
	if o == nil || IsNil(o.MaxClockDrift) {
		var ret int32
		return ret
	}
	return *o.MaxClockDrift
}

// GetMaxClockDriftOk returns a tuple with the MaxClockDrift field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponsesIbcClient) GetMaxClockDriftOk() (*int32, bool) {
	if o == nil || IsNil(o.MaxClockDrift) {
		return nil, false
	}
	return o.MaxClockDrift, true
}

// HasMaxClockDrift returns a boolean if a field has been set.
func (o *ResponsesIbcClient) HasMaxClockDrift() bool {
	if o != nil && !IsNil(o.MaxClockDrift) {
		return true
	}

	return false
}

// SetMaxClockDrift gets a reference to the given int32 and assigns it to the MaxClockDrift field.
func (o *ResponsesIbcClient) SetMaxClockDrift(v int32) {
	o.MaxClockDrift = &v
}

// GetTrustLevelDenominator returns the TrustLevelDenominator field value if set, zero value otherwise.
func (o *ResponsesIbcClient) GetTrustLevelDenominator() int32 {
	if o == nil || IsNil(o.TrustLevelDenominator) {
		var ret int32
		return ret
	}
	return *o.TrustLevelDenominator
}

// GetTrustLevelDenominatorOk returns a tuple with the TrustLevelDenominator field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponsesIbcClient) GetTrustLevelDenominatorOk() (*int32, bool) {
	if o == nil || IsNil(o.TrustLevelDenominator) {
		return nil, false
	}
	return o.TrustLevelDenominator, true
}

// HasTrustLevelDenominator returns a boolean if a field has been set.
func (o *ResponsesIbcClient) HasTrustLevelDenominator() bool {
	if o != nil && !IsNil(o.TrustLevelDenominator) {
		return true
	}

	return false
}

// SetTrustLevelDenominator gets a reference to the given int32 and assigns it to the TrustLevelDenominator field.
func (o *ResponsesIbcClient) SetTrustLevelDenominator(v int32) {
	o.TrustLevelDenominator = &v
}

// GetTrustLevelNumerator returns the TrustLevelNumerator field value if set, zero value otherwise.
func (o *ResponsesIbcClient) GetTrustLevelNumerator() int32 {
	if o == nil || IsNil(o.TrustLevelNumerator) {
		var ret int32
		return ret
	}
	return *o.TrustLevelNumerator
}

// GetTrustLevelNumeratorOk returns a tuple with the TrustLevelNumerator field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponsesIbcClient) GetTrustLevelNumeratorOk() (*int32, bool) {
	if o == nil || IsNil(o.TrustLevelNumerator) {
		return nil, false
	}
	return o.TrustLevelNumerator, true
}

// HasTrustLevelNumerator returns a boolean if a field has been set.
func (o *ResponsesIbcClient) HasTrustLevelNumerator() bool {
	if o != nil && !IsNil(o.TrustLevelNumerator) {
		return true
	}

	return false
}

// SetTrustLevelNumerator gets a reference to the given int32 and assigns it to the TrustLevelNumerator field.
func (o *ResponsesIbcClient) SetTrustLevelNumerator(v int32) {
	o.TrustLevelNumerator = &v
}

// GetTrustingPeriod returns the TrustingPeriod field value if set, zero value otherwise.
func (o *ResponsesIbcClient) GetTrustingPeriod() int32 {
	if o == nil || IsNil(o.TrustingPeriod) {
		var ret int32
		return ret
	}
	return *o.TrustingPeriod
}

// GetTrustingPeriodOk returns a tuple with the TrustingPeriod field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponsesIbcClient) GetTrustingPeriodOk() (*int32, bool) {
	if o == nil || IsNil(o.TrustingPeriod) {
		return nil, false
	}
	return o.TrustingPeriod, true
}

// HasTrustingPeriod returns a boolean if a field has been set.
func (o *ResponsesIbcClient) HasTrustingPeriod() bool {
	if o != nil && !IsNil(o.TrustingPeriod) {
		return true
	}

	return false
}

// SetTrustingPeriod gets a reference to the given int32 and assigns it to the TrustingPeriod field.
func (o *ResponsesIbcClient) SetTrustingPeriod(v int32) {
	o.TrustingPeriod = &v
}

// GetTxHash returns the TxHash field value if set, zero value otherwise.
func (o *ResponsesIbcClient) GetTxHash() *os.File {
	if o == nil || IsNil(o.TxHash) {
		var ret *os.File
		return ret
	}
	return *o.TxHash
}

// GetTxHashOk returns a tuple with the TxHash field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponsesIbcClient) GetTxHashOk() (**os.File, bool) {
	if o == nil || IsNil(o.TxHash) {
		return nil, false
	}
	return o.TxHash, true
}

// HasTxHash returns a boolean if a field has been set.
func (o *ResponsesIbcClient) HasTxHash() bool {
	if o != nil && !IsNil(o.TxHash) {
		return true
	}

	return false
}

// SetTxHash gets a reference to the given *os.File and assigns it to the TxHash field.
func (o *ResponsesIbcClient) SetTxHash(v *os.File) {
	o.TxHash = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *ResponsesIbcClient) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponsesIbcClient) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *ResponsesIbcClient) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *ResponsesIbcClient) SetType(v string) {
	o.Type = &v
}

// GetUnbondingPeriod returns the UnbondingPeriod field value if set, zero value otherwise.
func (o *ResponsesIbcClient) GetUnbondingPeriod() int32 {
	if o == nil || IsNil(o.UnbondingPeriod) {
		var ret int32
		return ret
	}
	return *o.UnbondingPeriod
}

// GetUnbondingPeriodOk returns a tuple with the UnbondingPeriod field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponsesIbcClient) GetUnbondingPeriodOk() (*int32, bool) {
	if o == nil || IsNil(o.UnbondingPeriod) {
		return nil, false
	}
	return o.UnbondingPeriod, true
}

// HasUnbondingPeriod returns a boolean if a field has been set.
func (o *ResponsesIbcClient) HasUnbondingPeriod() bool {
	if o != nil && !IsNil(o.UnbondingPeriod) {
		return true
	}

	return false
}

// SetUnbondingPeriod gets a reference to the given int32 and assigns it to the UnbondingPeriod field.
func (o *ResponsesIbcClient) SetUnbondingPeriod(v int32) {
	o.UnbondingPeriod = &v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *ResponsesIbcClient) GetUpdatedAt() time.Time {
	if o == nil || IsNil(o.UpdatedAt) {
		var ret time.Time
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponsesIbcClient) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *ResponsesIbcClient) HasUpdatedAt() bool {
	if o != nil && !IsNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given time.Time and assigns it to the UpdatedAt field.
func (o *ResponsesIbcClient) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = &v
}

func (o ResponsesIbcClient) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ResponsesIbcClient) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ChainId) {
		toSerialize["chain_id"] = o.ChainId
	}
	if !IsNil(o.ConnectionCount) {
		toSerialize["connection_count"] = o.ConnectionCount
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["created_at"] = o.CreatedAt
	}
	if !IsNil(o.Creator) {
		toSerialize["creator"] = o.Creator
	}
	if !IsNil(o.FrozenRevisionHeight) {
		toSerialize["frozen_revision_height"] = o.FrozenRevisionHeight
	}
	if !IsNil(o.FrozenRevisionNumber) {
		toSerialize["frozen_revision_number"] = o.FrozenRevisionNumber
	}
	if !IsNil(o.Height) {
		toSerialize["height"] = o.Height
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.LatestRevisionHeight) {
		toSerialize["latest_revision_height"] = o.LatestRevisionHeight
	}
	if !IsNil(o.LatestRevisionNumber) {
		toSerialize["latest_revision_number"] = o.LatestRevisionNumber
	}
	if !IsNil(o.MaxClockDrift) {
		toSerialize["max_clock_drift"] = o.MaxClockDrift
	}
	if !IsNil(o.TrustLevelDenominator) {
		toSerialize["trust_level_denominator"] = o.TrustLevelDenominator
	}
	if !IsNil(o.TrustLevelNumerator) {
		toSerialize["trust_level_numerator"] = o.TrustLevelNumerator
	}
	if !IsNil(o.TrustingPeriod) {
		toSerialize["trusting_period"] = o.TrustingPeriod
	}
	if !IsNil(o.TxHash) {
		toSerialize["tx_hash"] = o.TxHash
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if !IsNil(o.UnbondingPeriod) {
		toSerialize["unbonding_period"] = o.UnbondingPeriod
	}
	if !IsNil(o.UpdatedAt) {
		toSerialize["updated_at"] = o.UpdatedAt
	}
	return toSerialize, nil
}

type NullableResponsesIbcClient struct {
	value *ResponsesIbcClient
	isSet bool
}

func (v NullableResponsesIbcClient) Get() *ResponsesIbcClient {
	return v.value
}

func (v *NullableResponsesIbcClient) Set(val *ResponsesIbcClient) {
	v.value = val
	v.isSet = true
}

func (v NullableResponsesIbcClient) IsSet() bool {
	return v.isSet
}

func (v *NullableResponsesIbcClient) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResponsesIbcClient(val *ResponsesIbcClient) *NullableResponsesIbcClient {
	return &NullableResponsesIbcClient{value: val, isSet: true}
}

func (v NullableResponsesIbcClient) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResponsesIbcClient) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


