/*
Celenium API

Celenium TEST API is a powerful tool to access all blockchain data that is processed and indexed by our proprietary indexer. With Celenium API you can retrieve all historical data, off-chain data, blobs and statistics through our REST API. Celenium API indexer are open source, which allows you to not depend on third-party services. You can clone, build and run them independently, giving you full control over all components. If you have any questions or feature requests, please feel free to contact us. We appreciate your feedback!

API version: 1.0
Contact: celenium@pklabs.me
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package celenium

import (
	"encoding/json"
)

// checks if the HandlerError type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &HandlerError{}

// HandlerError struct for HandlerError
type HandlerError struct {
	Message *string `json:"message,omitempty"`
}

// NewHandlerError instantiates a new HandlerError object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewHandlerError() *HandlerError {
	this := HandlerError{}
	return &this
}

// NewHandlerErrorWithDefaults instantiates a new HandlerError object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewHandlerErrorWithDefaults() *HandlerError {
	this := HandlerError{}
	return &this
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *HandlerError) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HandlerError) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *HandlerError) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *HandlerError) SetMessage(v string) {
	o.Message = &v
}

func (o HandlerError) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o HandlerError) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	return toSerialize, nil
}

type NullableHandlerError struct {
	value *HandlerError
	isSet bool
}

func (v NullableHandlerError) Get() *HandlerError {
	return v.value
}

func (v *NullableHandlerError) Set(val *HandlerError) {
	v.value = val
	v.isSet = true
}

func (v NullableHandlerError) IsSet() bool {
	return v.isSet
}

func (v *NullableHandlerError) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableHandlerError(val *HandlerError) *NullableHandlerError {
	return &NullableHandlerError{value: val, isSet: true}
}

func (v NullableHandlerError) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableHandlerError) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


