/*
Celenium API

Celenium API is a powerful tool to access all blockchain data that is processed and indexed by our proprietary indexer. With Celenium API you can retrieve all historical data, off-chain data, blobs and statistics through our REST API. Celenium API indexer are open source, which allows you to not depend on third-party services. You can clone, build and run them independently, giving you full control over all components. If you have any questions or feature requests, please feel free to contact us. We appreciate your feedback!

API version: 1.0
Contact: celenium@pklabs.me
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package celenium

import (
	"encoding/json"
)

// checks if the ResponsesDistributionItem type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ResponsesDistributionItem{}

// ResponsesDistributionItem struct for ResponsesDistributionItem
type ResponsesDistributionItem struct {
	Name *string `json:"name,omitempty"`
	Value *string `json:"value,omitempty"`
}

// NewResponsesDistributionItem instantiates a new ResponsesDistributionItem object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResponsesDistributionItem() *ResponsesDistributionItem {
	this := ResponsesDistributionItem{}
	return &this
}

// NewResponsesDistributionItemWithDefaults instantiates a new ResponsesDistributionItem object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResponsesDistributionItemWithDefaults() *ResponsesDistributionItem {
	this := ResponsesDistributionItem{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *ResponsesDistributionItem) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponsesDistributionItem) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *ResponsesDistributionItem) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *ResponsesDistributionItem) SetName(v string) {
	o.Name = &v
}

// GetValue returns the Value field value if set, zero value otherwise.
func (o *ResponsesDistributionItem) GetValue() string {
	if o == nil || IsNil(o.Value) {
		var ret string
		return ret
	}
	return *o.Value
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponsesDistributionItem) GetValueOk() (*string, bool) {
	if o == nil || IsNil(o.Value) {
		return nil, false
	}
	return o.Value, true
}

// HasValue returns a boolean if a field has been set.
func (o *ResponsesDistributionItem) HasValue() bool {
	if o != nil && !IsNil(o.Value) {
		return true
	}

	return false
}

// SetValue gets a reference to the given string and assigns it to the Value field.
func (o *ResponsesDistributionItem) SetValue(v string) {
	o.Value = &v
}

func (o ResponsesDistributionItem) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ResponsesDistributionItem) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Value) {
		toSerialize["value"] = o.Value
	}
	return toSerialize, nil
}

type NullableResponsesDistributionItem struct {
	value *ResponsesDistributionItem
	isSet bool
}

func (v NullableResponsesDistributionItem) Get() *ResponsesDistributionItem {
	return v.value
}

func (v *NullableResponsesDistributionItem) Set(val *ResponsesDistributionItem) {
	v.value = val
	v.isSet = true
}

func (v NullableResponsesDistributionItem) IsSet() bool {
	return v.isSet
}

func (v *NullableResponsesDistributionItem) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResponsesDistributionItem(val *ResponsesDistributionItem) *NullableResponsesDistributionItem {
	return &NullableResponsesDistributionItem{value: val, isSet: true}
}

func (v NullableResponsesDistributionItem) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResponsesDistributionItem) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


