/*
Celenium API

Celenium API is a powerful tool to access all blockchain data that is processed and indexed by our proprietary indexer. With Celenium API you can retrieve all historical data, off-chain data, blobs and statistics through our REST API. Celenium API indexer are open source, which allows you to not depend on third-party services. You can clone, build and run them independently, giving you full control over all components. If you have any questions or feature requests, please feel free to contact us. We appreciate your feedback!

API version: 1.0
Contact: celenium@pklabs.me
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package celenium

import (
	"encoding/json"
)

// checks if the ResponsesShortAddress type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ResponsesShortAddress{}

// ResponsesShortAddress struct for ResponsesShortAddress
type ResponsesShortAddress struct {
	Celestials *ResponsesCelestial `json:"celestials,omitempty"`
	Hash *string `json:"hash,omitempty"`
}

// NewResponsesShortAddress instantiates a new ResponsesShortAddress object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResponsesShortAddress() *ResponsesShortAddress {
	this := ResponsesShortAddress{}
	return &this
}

// NewResponsesShortAddressWithDefaults instantiates a new ResponsesShortAddress object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResponsesShortAddressWithDefaults() *ResponsesShortAddress {
	this := ResponsesShortAddress{}
	return &this
}

// GetCelestials returns the Celestials field value if set, zero value otherwise.
func (o *ResponsesShortAddress) GetCelestials() ResponsesCelestial {
	if o == nil || IsNil(o.Celestials) {
		var ret ResponsesCelestial
		return ret
	}
	return *o.Celestials
}

// GetCelestialsOk returns a tuple with the Celestials field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponsesShortAddress) GetCelestialsOk() (*ResponsesCelestial, bool) {
	if o == nil || IsNil(o.Celestials) {
		return nil, false
	}
	return o.Celestials, true
}

// HasCelestials returns a boolean if a field has been set.
func (o *ResponsesShortAddress) HasCelestials() bool {
	if o != nil && !IsNil(o.Celestials) {
		return true
	}

	return false
}

// SetCelestials gets a reference to the given ResponsesCelestial and assigns it to the Celestials field.
func (o *ResponsesShortAddress) SetCelestials(v ResponsesCelestial) {
	o.Celestials = &v
}

// GetHash returns the Hash field value if set, zero value otherwise.
func (o *ResponsesShortAddress) GetHash() string {
	if o == nil || IsNil(o.Hash) {
		var ret string
		return ret
	}
	return *o.Hash
}

// GetHashOk returns a tuple with the Hash field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponsesShortAddress) GetHashOk() (*string, bool) {
	if o == nil || IsNil(o.Hash) {
		return nil, false
	}
	return o.Hash, true
}

// HasHash returns a boolean if a field has been set.
func (o *ResponsesShortAddress) HasHash() bool {
	if o != nil && !IsNil(o.Hash) {
		return true
	}

	return false
}

// SetHash gets a reference to the given string and assigns it to the Hash field.
func (o *ResponsesShortAddress) SetHash(v string) {
	o.Hash = &v
}

func (o ResponsesShortAddress) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ResponsesShortAddress) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Celestials) {
		toSerialize["celestials"] = o.Celestials
	}
	if !IsNil(o.Hash) {
		toSerialize["hash"] = o.Hash
	}
	return toSerialize, nil
}

type NullableResponsesShortAddress struct {
	value *ResponsesShortAddress
	isSet bool
}

func (v NullableResponsesShortAddress) Get() *ResponsesShortAddress {
	return v.value
}

func (v *NullableResponsesShortAddress) Set(val *ResponsesShortAddress) {
	v.value = val
	v.isSet = true
}

func (v NullableResponsesShortAddress) IsSet() bool {
	return v.isSet
}

func (v *NullableResponsesShortAddress) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResponsesShortAddress(val *ResponsesShortAddress) *NullableResponsesShortAddress {
	return &NullableResponsesShortAddress{value: val, isSet: true}
}

func (v NullableResponsesShortAddress) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResponsesShortAddress) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


