name: Generate Celenium API Go

on:
  repository_dispatch:
    types: [tag_created]

jobs:
  triggered_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Cleanup old client
        run: rm -rf celenium-api-go/
          
      - name: Generate API client
        uses: openapitools/openapi-generator-cli@v2.1.8
        with:
          generator-name: go
          input-spec: https://api.celenium.io/v1/swagger/doc.json
          output: ./celenium-api-go
          additional-properties: packageName=celenium
          generator-cli-args: "--skip-validate-spec"
          
      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"

      - name: Commit and push changes
        env:
          PAT_TOKEN: ${{ secrets.PAT }}
        run: |
          git add .
          git commit -m "${{ github.event.client_payload.tag }}"
          git push https://x-access-token:${PAT_TOKEN}@github.com/${{ github.repository }}.git