name: Generate API

on:
  repository_dispatch:

jobs:
  trigger_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Print message
        run: echo "This workflow was triggered by a tag in another repository."

  