name: Generate Celenium API Go

on:
  repository_dispatch:
    types: [tag_created]

jobs:
  triggered_job:
    
    docker run --rm \
    -v "${PWD}/Projects:/local" openapitools/openapi-generator-cli generate \
    -i https://raw.githubusercontent.com/celenium-io/celestia-indexer/v1.10.1/cmd/api/docs/swagger.json \
    -g go \
    -p packageName=celenium --skip-validate-spec \
    -o /local/mismirnov/celenium-api-go --git-repo-id celenium-api-go --git-user-id mismirnov
    
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      issues: write
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Delete all files except .github/workflows and LICENSE
        run: |
          find . -mindepth 1 \
            ! -name '.git' \
            ! -path './.github/workflows*' \
            ! -name 'LICENSE' \
            -exec rm -rf {} +

      - name: Generate API client
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/local openapitools/openapi-generator-cli generate \
            -i https://raw.githubusercontent.com/mismirnov/celestia-indexer/${{ github.event.client_payload.tag }}/cmd/api/docs/swagger.json \
            -g go \
            -o /local \
            -p packageName=celenium --skip-validate-spec
          
      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"

      - name: Commit and push changes
        run: |
          git add .
          git commit -m "${{ github.event.client_payload.tag }}"
          git push https://x-access-token:${{ secrets.PAT }}@github.com/${{ github.repository }}.git